spring:
  application:
    name: CONFIG-SERVER-SERVICE
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rjtkumar007/SpringMicroServiceAppConfig.git
          clone-on-start: true
          
server:
  port: 8086
  