server:
  port: 9191
spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:8086
  
  cloud:
    gateway:
      routes:
        - id: product-service
          uri: lb://product-service 
          predicates:
            - Path=/api/products
          filters:
            - AuthenticationFilter
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders
          filters:
            - AuthenticationFilter
        - id: inventory-service
          uri: lb://inventory-service
          predicates:
            - Path=/api/inventory
        - id: auth-security-service
          uri: lb://auth-security-service
          predicates:
            - Path=/api/auth/**
    circuitbreaker:
      resilience4j:
        enabled: true
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
          - health
          - zipkin
          - info
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
    
resilience4j:
  circuitbreaker:
    instances:
      order-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true

logging:
  level:
    root: INFO
