server:
  port: 8084
  
spring:
  application:
    name: AUTH-SECURITY-SERVICE
  config:
    import: configserver:http://localhost:8086
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/user-credential
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  tracing:
    enabled: true
    sampling:
      probability: 1
  zipkin:
    tracing:
      endpoint: http://localhost:9411/zipkin/