server:
  port: 8084
  
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
      
spring:
  application:
    name: AUTH-SECURITY-SERVICE
  datasource:
    username: root
    password: admin
    url: jdbc:mysql://localhost:3306/user-credential
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
      
      