server:
  port: 8081
spring:
  application:
    name: ORDER-SERVICE
  datasource:
    username: root
    name: root
    password: admin
    url: jdbc:mysql://localhost:3306/order-service
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - zipkin
          - info
  health:
    circuitbreakers:
      enabled: true    
  endpoint:
    health:
      show-details: always
  tracing:
    enabled: true
    sampling:
      probability: 1.0
      
resilience4j:
  circuitbreaker:
    instances:
      order-service:
        sliding-window-type: COUNT_BASED
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        register-health-indicator: true    

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka


tracing:
  zipkin:
    http:
      url: http://localhost:9411
    enabled: true
    sampler:
      probability: 1
  