spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: mongodb://localhost:27017/
  config:
    import: configserver:http://localhost:8086

server:
  port: 8080

management:
  tracing:
    enabled: true
    sampling:
      probability: 1.0
      

